//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L3C {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsViewMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsViewMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L3C.StringsViewMenu", typeof(StringsViewMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Cirkel..
        /// </summary>
        internal static string Circle_Prompt {
            get {
                return ResourceManager.GetString("Circle_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Rätblock..
        /// </summary>
        internal static string Cuboid_Prompt {
            get {
                return ResourceManager.GetString("Cuboid_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Cylinder..
        /// </summary>
        internal static string Cylinder_Prompt {
            get {
                return ResourceManager.GetString("Cylinder_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Ellipse..
        /// </summary>
        internal static string Ellipse_Prompt {
            get {
                return ResourceManager.GetString("Ellipse_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ={0}=.
        /// </summary>
        internal static string EqualsFormat {
            get {
                return ResourceManager.GetString("EqualsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------.
        /// </summary>
        internal static string FrameMinus {
            get {
                return ResourceManager.GetString("FrameMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------.
        /// </summary>
        internal static string FrameMinusTwo {
            get {
                return ResourceManager.GetString("FrameMinusTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figur      Längd Bredd  Höjd   Mantelarea Begräns.area        Volym.
        /// </summary>
        internal static string FrameSpecifiedTwo {
            get {
                return ResourceManager.GetString("FrameSpecifiedTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =====================================.
        /// </summary>
        internal static string FramOfEquals {
            get {
                return ResourceManager.GetString("FramOfEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figur      Längd Bredd  Omkrets    Area.
        /// </summary>
        internal static string FramSpecifiedOne {
            get {
                return ResourceManager.GetString("FramSpecifiedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =              Detaljer             =.
        /// </summary>
        internal static string MiddleFrameDetails {
            get {
                return ResourceManager.GetString("MiddleFrameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =         Geometriska figurer       =.
        /// </summary>
        internal static string MiddleFrameGeometriska {
            get {
                return ResourceManager.GetString("MiddleFrameGeometriska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =                                   =.
        /// </summary>
        internal static string OnlyEquals {
            get {
                return ResourceManager.GetString("OnlyEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. Avsluta..
        /// </summary>
        internal static string Quit_Prompt {
            get {
                return ResourceManager.GetString("Quit_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Slumpa 2D-figurer..
        /// </summary>
        internal static string Random2D_Prompt {
            get {
                return ResourceManager.GetString("Random2D_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Slumpa 3d-figurer..
        /// </summary>
        internal static string Random3D_Prompt {
            get {
                return ResourceManager.GetString("Random3D_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange menyval [0-8]:.
        /// </summary>
        internal static string ReadNumber_Prompt {
            get {
                return ResourceManager.GetString("ReadNumber_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Rektangel..
        /// </summary>
        internal static string Rektangle_Prompt {
            get {
                return ResourceManager.GetString("Rektangle_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Sphere.
        /// </summary>
        internal static string Sphere_Prompt {
            get {
                return ResourceManager.GetString("Sphere_Prompt", resourceCulture);
            }
        }
    }
}
