//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S2.L3C {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsFileR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsFileR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S2.L3C.StringsFileR", typeof(StringsFileR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirkel.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens diameter:.
        /// </summary>
        internal static string Circle_Propmt {
            get {
                return ResourceManager.GetString("Circle_Propmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omkrets.
        /// </summary>
        internal static string Circuit {
            get {
                return ResourceManager.GetString("Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rätblock.
        /// </summary>
        internal static string Cuboid {
            get {
                return ResourceManager.GetString("Cuboid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinder.
        /// </summary>
        internal static string Cylinder {
            get {
                return ResourceManager.GetString("Cylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! Ett fel har inträffat då figurens dimensioner tolkades..
        /// </summary>
        internal static string ErrorMessageDimensions_Prompt {
            get {
                return ResourceManager.GetString("ErrorMessageDimensions_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =====================================.
        /// </summary>
        internal static string FrameEqual {
            get {
                return ResourceManager.GetString("FrameEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längd.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens längd och bredd:.
        /// </summary>
        internal static string LengthNWidth_Prompt {
            get {
                return ResourceManager.GetString("LengthNWidth_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens längd, bredd och höjd:.
        /// </summary>
        internal static string LengthWidthNHeight_Prompt {
            get {
                return ResourceManager.GetString("LengthWidthNHeight_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantelarea.
        /// </summary>
        internal static string MantelArea {
            get {
                return ResourceManager.GetString("MantelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rektangel.
        /// </summary>
        internal static string Rektangle {
            get {
                return ResourceManager.GetString("Rektangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfär.
        /// </summary>
        internal static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange figurens radie:.
        /// </summary>
        internal static string Sphere_Prompt {
            get {
                return ResourceManager.GetString("Sphere_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begränsningsarea.
        /// </summary>
        internal static string TotalSurFaceArea {
            get {
                return ResourceManager.GetString("TotalSurFaceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volym.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bredd.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
